-- Create Schema
create schema if not exists neuronlink_analytics;

-- Grant usage to auth users (so they can insert logs)
grant usage on schema neuronlink_analytics to authenticated, anon;

-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- Create Table in new schema
create table neuronlink_analytics.user_events (
    id uuid default gen_random_uuid() primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users(id) on delete cascade not null,
    session_id uuid, -- Generated by app on load
    event_category text not null, -- 'AUTH', 'ANALYSIS', 'DATA', 'SYSTEM'
    event_type text not null,     -- 'QUERY_EXECUTE', 'FILTER_ADD'
    metadata jsonb default '{}'::jsonb -- Flexible payload
);

-- Enable RLS
alter table neuronlink_analytics.user_events enable row level security;

-- Policies
create policy "Users can insert their own events"
    on neuronlink_analytics.user_events for insert
    with check (auth.uid() = user_id);

create policy "Users can view their own events"
    on neuronlink_analytics.user_events for select
    using (auth.uid() = user_id);

-- Optional: Grant access to table
grant all on neuronlink_analytics.user_events to authenticated;
grant insert on neuronlink_analytics.user_events to anon; 
